const $=id=>document.getElementById(id);let step=1;const data={job:"",urgency:"",smart:{}};
const smart={
"Boiler / Heating":[["Boiler make / model (if known)","boiler","e.g. Worcester Greenstar"],["Error code (if shown)","error","e.g. E9"],["What do you currently have?","status","No heating / No hot water / Both / Other"]],
"Leak / Plumbing":[["Where is the leak?","location","e.g. kitchen ceiling, pipe under sink"],["Can you stop the water?","isolated","Yes / No / Not sure"],["Is water actively flowing now?","flowing","Yes / No"]],
"Bathroom / Installation":[["What are you looking for?","project","e.g. full bathroom refurbishment, shower replacement"],["When would you like the work done?","timing","e.g. next month"],["Have you already bought fittings?","fittings","Yes / No / Some"]],
"Other plumbing":[["What do you need help with?","other","Brief description"]]};
function buildSmart(){const box=$("smartQuestions");box.innerHTML="";data.smart={};(smart[data.job]||smart["Other plumbing"]).forEach(([label,key,ph])=>{const l=document.createElement("label");l.textContent=label;const input=document.createElement("input");input.placeholder=ph;input.dataset.key=key;l.appendChild(input);box.appendChild(l)})}
function show(){document.querySelectorAll(".screen").forEach(x=>x.classList.toggle("hidden",+x.dataset.step!==step));$("stepLabel").textContent="Step "+step+" of 6";$("bar").style.width=(step/6*100)+"%";$("back").classList.toggle("hidden",step===1);$("next").classList.toggle("hidden",step===1||step===4);$("next").textContent=step===6?"Create enquiry":"Continue"}
function choose(container,key){document.querySelectorAll("#"+container+" button").forEach(b=>b.onclick=()=>{data[key]=b.dataset.value;document.querySelectorAll("#"+container+" button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");if(key==="job"){buildSmart()}setTimeout(()=>{step++;show()},160)})}
choose("jobChoices","job");choose("urgencyChoices","urgency");
$("next").onclick=()=>{if(step===2){document.querySelectorAll("#smartQuestions input").forEach(i=>data.smart[i.dataset.key]=i.value.trim())}if(step===5&&!$("postcode").value.trim())return alert("Please enter the job postcode.");if(step===6){if(!$("name").value.trim()||!$("phone").value.trim())return alert("Please add your name and mobile number.");finish();return}step++;show()};
$("back").onclick=()=>{step--;show()};
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function label(k){return({boiler:"Boiler",error:"Error code",status:"Heating status",location:"Leak location",isolated:"Water isolated",flowing:"Water flowing",project:"Project",timing:"Preferred timing",fittings:"Fittings purchased",other:"Job"})[k]||k}
function finish(){const pics=$("photos").files.length;let smartRows=Object.entries(data.smart).filter(([,v])=>v).map(([k,v])=>"<p><b>"+esc(label(k))+":</b> "+esc(v)+"</p>").join("");$("summary").innerHTML="<h3>"+esc(data.job)+"</h3><p><b>Customer:</b> "+esc($("name").value)+"</p><p><b>Mobile:</b> "+esc($("phone").value)+"</p><p><b>Postcode:</b> "+esc($("postcode").value.toUpperCase())+"</p><p><b>Urgency:</b> "+esc(data.urgency)+"</p>"+smartRows+($("details").value?"<p><b>Extra details:</b> "+esc($("details").value)+"</p>":"")+"<p><b>Photos:</b> "+(pics?pics+" attached":"None")+"</p><p><b>Best contact time:</b> "+esc($("contactTime").value)+"</p>"+($("email").value?"<p><b>Email:</b> "+esc($("email").value)+"</p>":"");$("form").classList.add("hidden");$("done").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
$("restart").onclick=()=>location.reload();show();