const $=id=>document.getElementById(id);
const samples=[{id:"sample1",job:"Leak / Plumbing",urgency:"Emergency — now",postcode:"SA4 3XX",name:"Sarah Davies",phone:"07123 456789",details:"Water coming through kitchen ceiling.",smart:{location:"Kitchen ceiling",isolated:"No",flowing:"Yes"},photos:2,status:"New",assignee:"Unassigned",contactTime:"Any time"},{id:"sample2",job:"Boiler / Heating",urgency:"Within 24–48 hours",postcode:"SA3 4XX",name:"David Morgan",phone:"07987 654321",details:"Boiler stopped overnight.",smart:{boiler:"Worcester Greenstar",error:"EA",status:"No heating"},photos:1,status:"Contacting",assignee:"Shawn",contactTime:"Afternoon"},{id:"sample3",job:"Bathroom / Installation",urgency:"Planning / quote",postcode:"SA4 6XX",name:"Emma Jones",phone:"07700 900123",details:"Full bathroom refurbishment.",smart:{project:"Full bathroom refurbishment",timing:"Next month",fittings:"Some"},photos:4,status:"Booked",assignee:"Dan",contactTime:"Evening"}];
let latest=null;try{latest=JSON.parse(localStorage.getItem("trademateLatest"))}catch(e){}
if(latest){latest.id="latest";}let jobs=latest?[latest,...samples]:samples;
const labels={boiler:"Boiler",error:"Error code",status:"Heating status",location:"Leak location",isolated:"Water isolated",flowing:"Water flowing",project:"Project",timing:"Preferred timing",fittings:"Fittings purchased",other:"Job"};
function priority(u){return u.includes("Emergency")?"red":u.includes("24")?"amber":"green"}
function render(){const box=$("inbox");box.innerHTML=jobs.map(j=>`<button class="job-card" data-id="${j.id}"><span class="priority ${priority(j.urgency)}"></span><span class="job-main"><b>${esc(j.job)}</b><small>${esc(j.postcode)} · ${esc(j.name)}</small><small>${esc(j.urgency)}</small></span><span class="job-state">${esc(j.status)}<small>${esc(j.assignee)}</small></span><span class="chev">›</span></button>`).join("");document.querySelectorAll(".job-card").forEach(b=>b.onclick=()=>openJob(b.dataset.id));$("newCount").textContent=jobs.filter(j=>j.status==="New").length;$("contactCount").textContent=jobs.filter(j=>j.status==="Contacting").length;$("bookedCount").textContent=jobs.filter(j=>j.status==="Booked").length}
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function openJob(id){const j=jobs.find(x=>x.id===id);const smart=Object.entries(j.smart||{}).filter(([,v])=>v).map(([k,v])=>`<p><b>${esc(labels[k]||k)}:</b> ${esc(v)}</p>`).join("");$("jobDetail").innerHTML=`<span class="eyebrow">${esc(j.urgency)}</span><h2>${esc(j.job)}</h2><div class="summary"><p><b>Customer:</b> ${esc(j.name)}</p><p><b>Mobile:</b> ${esc(j.phone)}</p><p><b>Postcode:</b> ${esc(j.postcode)}</p>${smart}${j.details?`<p><b>Details:</b> ${esc(j.details)}</p>`:""}<p><b>Photos:</b> ${j.photos||0} attached</p><p><b>Best contact time:</b> ${esc(j.contactTime)}</p></div><div class="action-grid"><a class="button-link" href="tel:${esc(j.phone.replace(/\s/g,""))}">Call customer</a><label>Assign to<select id="assign"><option>Unassigned</option><option>Shawn</option><option>Ian</option><option>Dan</option><option>Team member 4</option><option>Team member 5</option><option>Team member 6</option></select></label><label>Status<select id="status"><option>New</option><option>Contacting</option><option>Quoted</option><option>Booked</option><option>Completed</option></select></label></div>`;$("assign").value=j.assignee;$("status").value=j.status;$("assign").onchange=e=>{j.assignee=e.target.value;save(j);render()};$("status").onchange=e=>{j.status=e.target.value;save(j);render()};$("jobPanel").classList.remove("hidden");document.querySelector(".stats").classList.add("hidden");document.querySelector("section:has(.inbox-title)").classList.add("hidden");window.scrollTo({top:0,behavior:"smooth"})}
function save(j){if(j.id==="latest")localStorage.setItem("trademateLatest",JSON.stringify(j))}
$("closeDetail").onclick=()=>{$("jobPanel").classList.add("hidden");document.querySelector(".stats").classList.remove("hidden");document.querySelector("section:has(.inbox-title)").classList.remove("hidden");render()};render();